### ISSUE TITLE
Explanation of InstanceDetector.m

### ISSUE THREAD

**Issue by Yuvika-M** [taimurhassan/TST#1]
Hey,

I reviewed your paper in CVPR, I wanted to know why do you have several labels?
Sixray only has 5 classes, yet this code below has several more labels dividing the classes.

Can you explain this approach?

https://github.com/taimurhassan/TST/blob/668e3ea339a66679ff6479499dd0756133387a92/instanceDetector.m#L19

Thanks
Yuvi :)

**Comment by taimurhassan** [comment]
Hi,
Yes, SIXray has 5 classes. But this framework performs instance segmentation of the overlapping items (belonging to same class) by treating them as different classes. So, for example, for the scan having two overlapping knives, you will have 2 separate labels for them (i.e., knife1 and knife2) rather than having one label representing a single blob for the two items.

Thanks
T.

**Comment by Yuvika-M** [comment]
Hey,

I understand now :) Did you just write code in the preprocessing step detect overlap and label in count order (Knife1, Knife2)?
Or did you label each object in the dataset physically, (Knife1->All butcher knives, Knife2->All daggers) so each object knife1, knife2, is mapped to a specific subcategory in the latent space?

Thanks
Yuvi :)

**Comment by taimurhassan** [comment]
Hi Yuvi,

Yes, for training, we first labelled each object instance ourselves and then we multiplied it with the original bbox annotation (converted to mask) that comes with the dataset. This last step was done just to ensure consistency of our annotations with the original markings. 

Thanks
Taimur

**Comment by Yuvika-M** [comment]
Hey Taimur,

Ah I see. You guys did a lot of work labelling! Is it possible for you to upload the updated SIXray dataset (positive samples only, with your modified annotations)? 

Thanks
Yuvi :)

**Comment by taimurhassan** [comment]
Hi Yuvi,

Yes, we are planning to release them soon with our future work.

Thanks,
Taimur

**Comment by Yashay** [comment]
Alright, thanks!

Yuvi :)

**Comment by Yuvika-M** [comment]
Alright thanks :)
