### ISSUE TITLE
segmentation labels?

### ISSUE THREAD

**Issue by jodumagpi** [taimurhassan/TST#2]
Hi! This work is great. However, when I looked at the datasets you linked, there seem to be no available labels for segmentation. I wonder if you labeled them yourselves? If so, do you plan to release it? It would be the only way to verify this work and use it a benchmark for other future research.

Thanks!

**Comment by taimurhassan** [comment]
Hi Jo,

Thank you for your email.

Yes, we intend to release the labels. However, due to some legal issues, we
are currently holding them. I will inform you once they are released.
Hopefully, it would be done in the next 2 to 3 months.

Kind Regards
Taimur

**Comment by jodumagpi** [comment]
Thanks for your kind reply!

**Comment by jodumagpi** [comment]
I hope you would also release your pre-trained models as well.
