### ISSUE TITLE
missing functions?

### ISSUE THREAD

**Issue by jodumagpi** [taimurhassan/TST#3]
Hi! I'm trying to test your code but parsing the annotation is throwing this error

```
error: 'xmlread' undefined near line 52 column 16
error: called from
    xml2struct at line 52 column 14
    gTGeneratorSIXray at line 17 column 9
```

Did you forget to include a function named xmlread???

**Comment by taimurhassan** [comment]
Hi,
'xmlread' is a MATLAB built-in function. Maybe there are some installation issues with the MATLAB that you are currently using, or maybe the required data import toolbox is not installed with the MATLAB.

Thanks,
Taimur

**Comment by jodumagpi** [comment]
Hi! You are right. I managed to make it work by updating my MatLab version. Thanks!

Also, I am assuming that this repository implements the default settings you used in your paper. Hence, this can be directly used to reproduce your work, right?

**Comment by taimurhassan** [comment]
Yes
